# Generated by Django 5.2.7 on 2025-10-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='description',
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
